# Generated by Django 5.1.2 on 2024-11-18 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('apikey', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_data', models.JSONField()),
                ('all_messages', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chatbot_session',
            },
        ),
        migrations.CreateModel(
            name='ContextData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_description', models.TextField()),
                ('context_example', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_length', models.PositiveIntegerField(default=500)),
                ('output_length', models.PositiveIntegerField(default=50)),
                ('limit_summary', models.PositiveIntegerField(default=1000)),
                ('conversation_timeout', models.IntegerField(default=10, help_text='Conversation Timeout in minutes')),
                ('interaction_language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('ZH', 'Mandarin'), ('HI', 'Hindi'), ('AR', 'Arabic'), ('BN', 'Bengali'), ('PT', 'Portuguese'), ('RU', 'Russian'), ('JA', 'Japanese'), ('DE', 'German'), ('BG', 'Bulgarian')], default='EN', help_text='Language for bot interactions', max_length=2)),
                ('bot_personality', models.CharField(choices=[('PROF', 'Professional'), ('FRI', 'Friendly'), ('FORM', 'Formal'), ('CAS', 'Casual'), ('ASS', 'Assistive'), ('HUM', 'Humorous'), ('EMP', 'Empathetic'), ('INF', 'Informative'), ('ENG', 'Engaging'), ('SAR', 'Sarcastic')], default='PROF', help_text='Personality style of the bot', max_length=4)),
                ('rate_limit', models.IntegerField(default=60, help_text='Maximum requests allowed per minute')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interactions', models.IntegerField()),
                ('daily_interactions', models.IntegerField(default=0)),
                ('monthly_interactions', models.IntegerField(default=0)),
                ('tokens_usage', models.IntegerField()),
                ('daily_tokens_usage', models.IntegerField(default=0)),
                ('monthly_tokens_usage', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
