# Generated by Django 5.1.2 on 2024-11-18 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chatbots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_chatbots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settings',
            name='chatbot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_settings', to='Chatbots.chatbot'),
        ),
        migrations.AddField(
            model_name='settings',
            name='context_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_context_data_settings', to='Chatbots.contextdata'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_chatbot_settings', to='Chatbots.settings'),
        ),
        migrations.AddField(
            model_name='usage',
            name='chatbot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_usage', to='Chatbots.chatbot'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='usage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_chatbot_usage', to='Chatbots.usage'),
        ),
    ]
