# Generated by Django 5.1.2 on 2024-11-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbots', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='interactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='tokens_usage',
            field=models.IntegerField(default=0),
        ),
    ]
