# Generated by Django 5.1.2 on 2024-11-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbots', '0004_settings_default_greeting_alter_chatbot_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='default_greeting',
            field=models.CharField(default='Hello! How can I help you today?', max_length=200),
        ),
    ]
