# Generated by Django 5.1.2 on 2024-12-11 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbots', '0006_allowedhost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_chatbot_settings', to='Chatbots.settings'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='usage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_chatbot_usage', to='Chatbots.usage'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='context_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_context_data_settings', to='Chatbots.contextdata'),
        ),
    ]
