# Generated by Django 5.1.2 on 2024-11-18 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(choices=[('mly', 'Monthly'), ('yky', 'Yearly'), ('ofr', 'Custom Offer')], default='mly', max_length=3)),
                ('method', models.CharField(choices=[('CC', 'Credit Card'), ('PP', 'PayPal'), ('BT', 'Bank Transfer'), ('CR', 'Cryptocurrency')], default='CC', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanFAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=20)),
                ('popular', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('benefits', models.ManyToManyField(blank=True, to='Subscriptions.planfas')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subscriptions.plan')),
            ],
        ),
    ]
